# <https://github.com/sol/hpack>

name: knuckleball
maintainer: XT
synopsis: Bot experiment
version: '0.0.0'
license: AGPL
category: Network
description: Bot experiment
ghc-options: -Wall
github: xtendo-org/knuckleball
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

library:
  source-dirs: library
  default-extensions:
  - OverloadedStrings
  dependencies:
  - base
  - network
  - tls

executables:
  knuckleball:
    source-dirs: executable
    ghc-options:
    - -Wall
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    default-extensions:
    - OverloadedStrings
    dependencies:
    - base
    - knuckleball

tests:
  knuckleball-test-suite:
    dependencies:
    - base
    - knuckleball
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite

benchmarks:
  knuckleball-benchmarks:
    dependencies:
    - base
    - knuckleball
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
