# <https://github.com/sol/hpack>

name: yukikaze-scs
maintainer: XT
synopsis: Bot experiment
version: '0.0.0'
license: AGPL
category: Network
description: Bot experiment
ghc-options: -Wall
github: xtendo-org/yukikaze-scs
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

library:
  source-dirs: library
  default-extensions:
  - OverloadedStrings
  - TemplateHaskell
  - RecordWildCards
  dependencies:
  - aeson
  - base
  - bytestring
  - network
  - pipes
  - rawfilepath
  - text
  - tls
  - yaml

executables:
  yukikaze-scs:
    source-dirs: executable
    ghc-options:
    - -Wall
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    default-extensions:
    - OverloadedStrings
    dependencies:
    - base
    - yukikaze-scs

tests:
  yukikaze-scs-test-suite:
    dependencies:
    - base
    - yukikaze-scs
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite

benchmarks:
  yukikaze-scs-benchmarks:
    dependencies:
    - base
    - yukikaze-scs
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
